### ISSUE TITLE
Improvements to the "is typing" function

### ISSUE THREAD

**Issue by fabiang7** [dsg-bielefeld/slurk#42] opened 2019-01-18 09:25 UTC
The core functionality is working, but I would like to see minor improvements:

- [x] If a user press "enter" (or in general: send a message), the typing-bit should be set to 0. Because its likely that he stops typing now. If he restarts typing, the bit is set to 1 again anyway.

- [x] If the second user joins my room, he triggers "is typing" even if he do not press anything. This also happens if a user rejoins the chat. 

- [ ] ~Make the "is typing" string dynamic: "is typing ." "is typing .." "is typing ..." "is typing ." (Little animation of the dots). This makes it more visible for turker~

**Comment by TimDiekmann** [comment] 2019-01-18 09:35
1. I'll set it to `-1` which means "not typing". `0` means, he just typed in the latest tick.

2. This was a problem in the initial version, but with 5370dafa5e8808315c4ec3a07ce4b9bda50ca2c8 this should be fixed. I cannot reproduce this. Steps I tried:
    1. Join test room with two clients
    2. Reloading page with some of the clients

    Did you test it with the latest version?

**Comment by fabiang7** [comment] 2019-01-24 11:02
Added a third point.

**Closed** 2019-02-06 13:39 UTC
Labels: Area: Client, Category: Enhancement
